name: SHARUCO - CI

on:
  push:
    branches:
      - master
    paths:
      - '/**'
      - '.github/workflows/ci.yml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**'
      - '.github/workflows/ci.yml'

jobs:
  build_lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Check the lint
        run: npm run lint

      - name: Archive lint report
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: lint-report.json
        if: failure()

      # TODO: we should have tests running on this project
      # but there are not yet available
      # - name: Unit tests
      #   run: yarn coverage
      # - name: Send report to codecov
      #   run: yarn codecov
      #   if: ${{ always() }}

      - name: Fix reports paths
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace@g' lint-report.json

      - name: Check the build
        run: npm run build
